"""Update Demandeur Schema

Revision ID: 845e54dafc23
Revises: b3b664754d8f
Create Date: 2022-11-06 12:44:27.584340

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '845e54dafc23'
down_revision = 'b3b664754d8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demandeur', sa.Column('selection_expiration_date', sa.DateTime(), nullable=True))
    op.drop_column('demandeur', 'expiration_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demandeur', sa.Column('expiration_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('demandeur', 'selection_expiration_date')
    # ### end Alembic commands ###
