"""Update Demandeur constraint

Revision ID: 8b3c20b729a0
Revises: dd2b7c802fd2
Create Date: 2022-11-05 20:06:09.170364

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8b3c20b729a0'
down_revision = 'dd2b7c802fd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('groupe')
    op.drop_table('qrcode')
    op.alter_column('demandeur', 'tel',
               existing_type=sa.VARCHAR(length=25),
               nullable=False)
    op.alter_column('demandeur', 'cni',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('demandeur', 'cni',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('demandeur', 'tel',
               existing_type=sa.VARCHAR(length=25),
               nullable=True)
    op.create_table('qrcode',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('owner', postgresql.ENUM('DEMANDEUR', 'GROUPE', name='choices'), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='qrcode_pkey')
    )
    op.create_table('groupe',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('demandeurs', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='groupe_pkey')
    )
    # ### end Alembic commands ###
