"""Initial migration

Revision ID: dd2b7c802fd2
Revises: 
Create Date: 2022-11-05 19:47:09.554101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd2b7c802fd2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demandeur', sa.Column('created_at', sa.String(length=100), nullable=True))
    op.add_column('demandeur', sa.Column('is_selected', sa.Boolean(), nullable=True))
    op.add_column('demandeur', sa.Column('expiration_date', sa.DateTime(), nullable=True))
    op.alter_column('demandeur', 'cni',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('user', 'is_deleted')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('demandeur', 'cni',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('demandeur', 'expiration_date')
    op.drop_column('demandeur', 'is_selected')
    op.drop_column('demandeur', 'created_at')
    # ### end Alembic commands ###
